---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-datadog-operator
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: datadog-operator
                addonChartVersion: 1.6.0
                addonChartRepository: https://helm.datadoghq.com
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 1.6.0
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values:
                addonChartVersion: 1.6.0
  template:
    metadata:
      name: addon-{{.name}}-{{.values.addonChart}}
      namespace: argocd
    spec:
      project: default
      sources:
        - repoURL: https://github.com/kungfoome/argocd-addons.git
          targetRevision: HEAD
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/addons/config/base/{{.values.addonChart}}/values.yaml
              - $values/addons/config/overlays/environment/{{.metadata.labels.environment}}/{{.values.addonChart}}/values.yaml
              - $values/addons/config/overlays/cluster/{{.name}}/{{.values.addonChart}}/values.yaml
      destination:
        namespace: '{{.values.addonChart}}'
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
